title: "Whitney Bullock"
logo: "/images/headshot.jpg"

description: >
  Hello!! Welcome to my portfolio. I am a Sr. Operations Manager specializing in global logistics strategies and cost optimization. 
  My GitHub highlights projects that solve real-world problems, showcase best practices, and push me to learn more. 
  I’m passionate about AI and automation, and I love collaborating with others on open-source initiatives.
  <br><br>

show_downloads: true
theme: jekyll-theme-minimal

github:
  repository: wbullock97/Whitney_Bullock_Portfolio
